allowBuilds:
  esbuild: true
  ffmpeg-static: true
  sharp: true
  ytdlp-nodejs: true
minimumReleaseAgeExclude:
  - mongoose@9.7.4
onlyBuiltDependencies:
  - esbuild
  - ffmpeg-static
  - sharp
  - youtube-dl-exec
