export const rtcRegionList = {
  null: "Automatic",
  "brazil": "Brazil",
  "hongkong": "Hong Kong",
  "india": "India",
  "japan": "Japan",
  "rotterdam": "Rotterdam",
  "singapore": "Singapore",
  "southafrica": "South Africa",
  "sydney": "Sydney",
  "us-central": "US Central",
  "us-east": "US East",
  "us-south": "US South",
  "us-west": "US West",
};
